name: style

on:
    pull_request:
    push:
        branches: ["main"]

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn

            - name: Run Prettier
              run: yarn prettier
